### ISSUE TITLE
Bug concepts: NFloat is apparently not specialized over Float

### ISSUE THREAD

**Issue by renehiemstra** [tpkessler/terra-playground#25]
When running `test_range.t` I get the following error:
```
    ./range.t:139: invalid conversion from FixedFloat(256) to uint64
        return [size_t](tmath.floor(v))
```
This is because dispatch is not correctly finding the right implementation. The first method is dispatched for `FixedFloat(256)` instead of the second method:
```
terraform floor(v : T) where {T : concept.Float}
    return [size_t](tmath.floor(v))
end

terraform floor(v : T) where {T : concept.NFloat}
    return [size_t](v:truncatetodouble())
end
```

**Comment by tpkessler** [comment]
This was fixed with commit d08ccacf16d447dcb9b038196e437dfd015b9317
